In [21]:
import pandas as pd
import pickle
import random
import torch

In [33]:
with open("./final_embeddings_real_fragments.pkl", "rb") as p:
    fragments = pickle.load(p)

fragments

[('B3EWP6',
  True,
  tensor([ 0.0304,  0.0447,  0.0225,  ..., -0.0383, -0.0474, -0.0110])),
 ('C0HJQ3',
  True,
  tensor([0.0863, 0.1244, 0.0286,  ..., 0.0359, 0.0548, 0.0968])),
 ('C0HLV7',
  True,
  tensor([-0.0122,  0.1261,  0.0340,  ...,  0.0537,  0.0494, -0.0272])),
 ('C7E9W0',
  True,
  tensor([-0.0153, -0.0129,  0.0091,  ...,  0.0120,  0.0673,  0.0076])),
 ('O02827',
  True,
  tensor([ 0.0507,  0.1159,  0.0178,  ...,  0.0253,  0.0021, -0.0138])),
 ('O08615',
  True,
  tensor([ 0.0442, -0.1129,  0.0857,  ...,  0.0442,  0.0444,  0.0616])),
 ('O13147',
  True,
  tensor([ 0.0405,  0.0966,  0.0323,  ...,  0.0227, -0.0393, -0.0136])),
 ('O13148',
  True,
  tensor([ 0.0840,  0.1470,  0.0406,  ...,  0.0217, -0.0270, -0.0062])),
 ('O35116',
  True,
  tensor([0.0345, 0.1111, 0.0501,  ..., 0.0476, 0.0099, 0.0002])),
 ('O35750',
  True,
  tensor([ 0.0390,  0.0550,  0.0165,  ..., -0.0084, -0.0364,  0.0375])),
 ('O55075',
  True,
  tensor([0.0573, 0.0978, 0.0534,  ..., 0.0308, 0.0406, 0.0076

In [35]:
len(fragments)

4806

In [34]:
unique = []

for item in fragments:
    is_duplicate = False
    for u in unique:
        if item[0] == u[0] and item[1] == u[1] and torch.equal(item[2], u[2]):
            is_duplicate = True
            break

    if not is_duplicate:
        unique.append(item)

len(unique)

4806

In [36]:
fragments = unique

In [26]:
with open("./final_embeddings_train.pkl", "rb") as p:
    train = pickle.load(p)

In [27]:
len(train)

93626

In [28]:
def deduplicate(data):
    unique = []
    for item in data:
        is_duplicate = False
        for u in unique:
            if item[0] == u[0] and item[1] == u[1] and item[2] == u[2] and torch.equal(item[3], u[3]):
                is_duplicate = True
                break

        if not is_duplicate:
            unique.append(item)

    return unique


In [29]:
train = deduplicate(train)

In [30]:
len(train)

85852

In [31]:
[entry for entry in train if entry[0] == "A9MH08"]

[('A9MH08',
  False,
  'complete',
  tensor([ 0.0270,  0.0671, -0.0068,  ..., -0.0022, -0.0519,  0.0330])),
 ('A9MH08',
  True,
  'terminal_N',
  tensor([ 0.0271,  0.0643, -0.0159,  ...,  0.0022, -0.0378,  0.0302]))]

In [32]:
frag_counts = 0
full_counts = 0

for entry in train:
    if entry[1]:
        frag_counts += 1
    else:
        full_counts += 1

print(frag_counts)
print(full_counts)

43428
42424


In [37]:
len(train)

85852

In [61]:
fragment_ids = [fragment[0] for fragment in fragments]
train_ids_not_fragment = [seq[0] for seq in train if not seq[1]]

In [62]:
new_ids = random.sample(train_ids_not_fragment, len(fragment_ids))
len(new_ids)

4806

In [63]:
new_ids = set(new_ids)

In [64]:
len(new_ids)

4806

In [65]:
cut_train = [entry for entry in train if entry[0] not in new_ids]

In [66]:
len(cut_train)

76380

In [46]:
fragments = [(entry[0], entry[1], "fragment", entry[2]) for entry in fragments]

In [67]:
len(fragments)

4806

In [68]:
fragments[0]

('B3EWP6',
 True,
 'fragment',
 tensor([ 0.0304,  0.0447,  0.0225,  ..., -0.0383, -0.0474, -0.0110]))

In [69]:
new_fragments = [entry for entry in fragments]

In [70]:
print(len(new_fragments))
new_fragments[0]

4806


('B3EWP6',
 True,
 'fragment',
 tensor([ 0.0304,  0.0447,  0.0225,  ..., -0.0383, -0.0474, -0.0110]))

In [71]:
for new_id in new_ids:
    entries = [entry for entry in train if entry[0] == new_id and not entry[1]]
    new_fragments += entries

In [72]:
len(new_fragments)

9612

In [74]:
new_fragments

[('B3EWP6',
  True,
  'fragment',
  tensor([ 0.0304,  0.0447,  0.0225,  ..., -0.0383, -0.0474, -0.0110])),
 ('C0HJQ3',
  True,
  'fragment',
  tensor([0.0863, 0.1244, 0.0286,  ..., 0.0359, 0.0548, 0.0968])),
 ('C0HLV7',
  True,
  'fragment',
  tensor([-0.0122,  0.1261,  0.0340,  ...,  0.0537,  0.0494, -0.0272])),
 ('C7E9W0',
  True,
  'fragment',
  tensor([-0.0153, -0.0129,  0.0091,  ...,  0.0120,  0.0673,  0.0076])),
 ('O02827',
  True,
  'fragment',
  tensor([ 0.0507,  0.1159,  0.0178,  ...,  0.0253,  0.0021, -0.0138])),
 ('O08615',
  True,
  'fragment',
  tensor([ 0.0442, -0.1129,  0.0857,  ...,  0.0442,  0.0444,  0.0616])),
 ('O13147',
  True,
  'fragment',
  tensor([ 0.0405,  0.0966,  0.0323,  ...,  0.0227, -0.0393, -0.0136])),
 ('O13148',
  True,
  'fragment',
  tensor([ 0.0840,  0.1470,  0.0406,  ...,  0.0217, -0.0270, -0.0062])),
 ('O35116',
  True,
  'fragment',
  tensor([0.0345, 0.1111, 0.0501,  ..., 0.0476, 0.0099, 0.0002])),
 ('O35750',
  True,
  'fragment',
  tensor([ 0.03

In [76]:
with open("./final_embeddings_new_fragments.pkl", "wb") as p:
    pickle.dump(new_fragments, p)

In [77]:
with open("./final_embeddings_train_corrected.pkl", "wb") as p:
    pickle.dump(train, p)

In [78]:
# fix validation
with open("./final_embeddings_val.pkl", "rb") as p:
    val = pickle.load(p)

In [79]:
len(val)

21391

In [80]:
val

[('O86312',
  False,
  'complete',
  tensor([ 0.0083, -0.0712, -0.0005,  ..., -0.0523,  0.0027, -0.0058])),
 ('Q58159',
  True,
  'terminal_N',
  tensor([-0.0161, -0.0454,  0.0357,  ...,  0.1176,  0.0356,  0.0287])),
 ('A8W3E3',
  True,
  'terminal_both',
  tensor([ 0.1001,  0.0314, -0.0019,  ..., -0.0462, -0.0054,  0.0150])),
 ('Q4FQ25',
  True,
  'internal_gap',
  tensor([ 0.0012, -0.0541,  0.0217,  ..., -0.0645,  0.0418,  0.0109])),
 ('Q9CCN2',
  False,
  'complete',
  tensor([ 0.0191, -0.0034,  0.0139,  ..., -0.0021, -0.0202,  0.0047])),
 ('Q5ZNC8',
  True,
  'mixed',
  tensor([-0.0808, -0.0168, -0.0464,  ...,  0.0938, -0.0317,  0.0549])),
 ('Q660I8',
  True,
  'terminal_N',
  tensor([ 0.0337,  0.0339, -0.0147,  ...,  0.0120,  0.0109,  0.0033])),
 ('A2CI97',
  True,
  'internal_gap',
  tensor([-0.0226, -0.0544,  0.0293,  ...,  0.0386,  0.0488,  0.0117])),
 ('P23448',
  False,
  'complete',
  tensor([0.0403, 0.0109, 0.0047,  ..., 0.0318, 0.0600, 0.0749])),
 ('Q8XHJ4',
  False,
  'co

In [81]:
val = deduplicate(val)

In [82]:
len(val)

21391

In [83]:
with open("./final_embeddings_test.pkl", "rb") as p:
    test = pickle.load(p)

In [84]:
len(test)

26759

In [85]:
test

[('Q0SI65',
  True,
  'terminal_N',
  tensor([ 0.0093, -0.0351, -0.0058,  ...,  0.0106, -0.0002, -0.0190])),
 ('Q28C60',
  True,
  'internal_gap',
  tensor([-0.0156, -0.0092,  0.0338,  ...,  0.0157,  0.0266,  0.0173])),
 ('Q1LPW9',
  True,
  'terminal_C',
  tensor([ 0.0503,  0.0598,  0.0233,  ..., -0.0462,  0.0219,  0.0611])),
 ('A3KN25',
  False,
  'complete',
  tensor([-0.0318,  0.0451,  0.0029,  ..., -0.0164,  0.0368,  0.0485])),
 ('Q8K9B9',
  True,
  'terminal_C',
  tensor([-0.0406,  0.0492, -0.0846,  ..., -0.0660, -0.0215,  0.0076])),
 ('Q8IZU2',
  True,
  'terminal_both',
  tensor([ 0.0170,  0.0130, -0.0002,  ..., -0.0380,  0.0163,  0.0131])),
 ('A1A033',
  True,
  'internal_gap',
  tensor([-0.0730, -0.0042,  0.0137,  ...,  0.0666, -0.0024,  0.0480])),
 ('Q9C115',
  False,
  'complete',
  tensor([ 0.0323, -0.0771, -0.0061,  ...,  0.0144,  0.0123, -0.0606])),
 ('Q88YI8',
  True,
  'mixed',
  tensor([ 0.0060,  0.0054,  0.0103,  ...,  0.0268, -0.0018,  0.0317])),
 ('A8GCK1',
  True,

In [86]:
test = deduplicate(test)

In [87]:
len(test)

26759